// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainingManager.Data;

#nullable disable

namespace TrainingManager.Migrations
{
    [DbContext(typeof(TrainingContext))]
    [Migration("20260528172608_remove-updated-at-and-created-at-in-day-exercise")]
    partial class removeupdatedatandcreatedatindayexercise
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainingManager.Models.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("OrderInProgram")
                        .HasColumnType("integer")
                        .HasColumnName("orderInProgram");

                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("days");
                });

            modelBuilder.Entity("TrainingManager.Models.DayExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayId")
                        .HasColumnType("integer")
                        .HasColumnName("dayId");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("exerciseId");

                    b.Property<int>("OrderInDay")
                        .HasColumnType("integer")
                        .HasColumnName("orderInDay");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("dayExercises");
                });

            modelBuilder.Entity("TrainingManager.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("exercises");
                });

            modelBuilder.Entity("TrainingManager.Models.PlannedWorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("DayExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("dayExerciseId");

                    b.Property<int>("OrderInExercise")
                        .HasColumnType("integer")
                        .HasColumnName("orderInExercise");

                    b.Property<int?>("PlannedRepsCount")
                        .HasColumnType("integer")
                        .HasColumnName("plannedRepsCount");

                    b.Property<double?>("PlannedWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("plannedSetsWeight");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("DayExerciseId");

                    b.ToTable("plannedWorkoutSets");
                });

            modelBuilder.Entity("TrainingManager.Models.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("DaysCount")
                        .HasColumnType("integer")
                        .HasColumnName("daysCount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startDate");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("trainingPrograms");
                });

            modelBuilder.Entity("TrainingManager.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("DayId")
                        .HasColumnType("integer")
                        .HasColumnName("dayId");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.ToTable("workoutSessions");
                });

            modelBuilder.Entity("TrainingManager.Models.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("dayExerciseId");

                    b.Property<bool>("IsComplited")
                        .HasColumnType("boolean")
                        .HasColumnName("isCompleted");

                    b.Property<int>("OrderInExercise")
                        .HasColumnType("integer")
                        .HasColumnName("orderInExercise");

                    b.Property<int?>("RepsCount")
                        .HasColumnType("integer")
                        .HasColumnName("repsCount");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weigth");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("WorkoutSessionId");

                    b.HasKey("Id");

                    b.HasIndex("DayExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("workoutSets");
                });

            modelBuilder.Entity("TrainingManager.Models.Day", b =>
                {
                    b.HasOne("TrainingManager.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("ProgramDays")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("TrainingManager.Models.DayExercise", b =>
                {
                    b.HasOne("TrainingManager.Models.Day", "Day")
                        .WithMany("DayExercises")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingManager.Models.Exercise", "Exercise")
                        .WithMany("DayExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("TrainingManager.Models.PlannedWorkoutSet", b =>
                {
                    b.HasOne("TrainingManager.Models.DayExercise", "DayExercise")
                        .WithMany("PlannedWorkoutSets")
                        .HasForeignKey("DayExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayExercise");
                });

            modelBuilder.Entity("TrainingManager.Models.WorkoutSession", b =>
                {
                    b.HasOne("TrainingManager.Models.Day", "Day")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");
                });

            modelBuilder.Entity("TrainingManager.Models.WorkoutSet", b =>
                {
                    b.HasOne("TrainingManager.Models.DayExercise", "DayExercise")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("DayExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingManager.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayExercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("TrainingManager.Models.Day", b =>
                {
                    b.Navigation("DayExercises");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("TrainingManager.Models.DayExercise", b =>
                {
                    b.Navigation("PlannedWorkoutSets");

                    b.Navigation("WorkoutSets");
                });

            modelBuilder.Entity("TrainingManager.Models.Exercise", b =>
                {
                    b.Navigation("DayExercises");
                });

            modelBuilder.Entity("TrainingManager.Models.TrainingProgram", b =>
                {
                    b.Navigation("ProgramDays");
                });

            modelBuilder.Entity("TrainingManager.Models.WorkoutSession", b =>
                {
                    b.Navigation("WorkoutSets");
                });
#pragma warning restore 612, 618
        }
    }
}
