// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainingManager.Data;

#nullable disable

namespace TrainingManager.Migrations
{
    [DbContext(typeof(TrainingContext))]
    partial class TrainingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainingManager.Models.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Order_index")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("TrainingManager.Models.DayExercises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayId")
                        .HasColumnType("integer");

                    b.Property<int>("ExercisesId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderInDay")
                        .HasColumnType("integer");

                    b.Property<int?>("PlainedReps")
                        .HasColumnType("integer");

                    b.Property<int?>("PlainedSets")
                        .HasColumnType("integer");

                    b.Property<double?>("PlainedWeight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("ExercisesId");

                    b.ToTable("DayExercises");
                });

            modelBuilder.Entity("TrainingManager.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("TrainingManager.Models.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("TrainingManager.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.ToTable("WorkoutSession");
                });

            modelBuilder.Entity("TrainingManager.Models.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayExercisesId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsComplited")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderInExercises")
                        .HasColumnType("integer");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DayExercisesId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("WorkoutSet");
                });

            modelBuilder.Entity("TrainingManager.Models.Day", b =>
                {
                    b.HasOne("TrainingManager.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("ProgramDays")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("TrainingManager.Models.DayExercises", b =>
                {
                    b.HasOne("TrainingManager.Models.Day", "Day")
                        .WithMany("DayExercises")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingManager.Models.Exercise", "Exercises")
                        .WithMany("DayExercises")
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("TrainingManager.Models.WorkoutSession", b =>
                {
                    b.HasOne("TrainingManager.Models.Day", "Day")
                        .WithMany("WorkoutSession")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");
                });

            modelBuilder.Entity("TrainingManager.Models.WorkoutSet", b =>
                {
                    b.HasOne("TrainingManager.Models.DayExercises", "DayExercises")
                        .WithMany("WorkoutSet")
                        .HasForeignKey("DayExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingManager.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayExercises");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("TrainingManager.Models.Day", b =>
                {
                    b.Navigation("DayExercises");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("TrainingManager.Models.DayExercises", b =>
                {
                    b.Navigation("WorkoutSet");
                });

            modelBuilder.Entity("TrainingManager.Models.Exercise", b =>
                {
                    b.Navigation("DayExercises");
                });

            modelBuilder.Entity("TrainingManager.Models.TrainingProgram", b =>
                {
                    b.Navigation("ProgramDays");
                });

            modelBuilder.Entity("TrainingManager.Models.WorkoutSession", b =>
                {
                    b.Navigation("WorkoutSets");
                });
#pragma warning restore 612, 618
        }
    }
}
